# Generated by Django 6.0.5 on 2026-05-07 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('vehicle', models.CharField(choices=[('bike', 'Bike'), ('motorcycle', 'Motorcycle'), ('car', 'Car'), ('foot', 'On Foot')], default='motorcycle', max_length=50)),
                ('default_start_lat', models.FloatField(blank=True, help_text='Default starting latitude (e.g. warehouse)', null=True)),
                ('default_start_lng', models.FloatField(blank=True, help_text='Default starting longitude (e.g. warehouse)', null=True)),
                ('default_start_address', models.CharField(blank=True, help_text='Default starting address description', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('courier_start_lat', models.FloatField(blank=True, null=True)),
                ('courier_start_lng', models.FloatField(blank=True, null=True)),
                ('courier_start_address', models.CharField(blank=True, max_length=255)),
                ('ai_response', models.TextField(blank=True)),
                ('ai_optimized_order', models.TextField(blank=True, help_text='JSON list of optimized point IDs')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek')], default='en', max_length=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='routes.courier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('recipient_name', models.CharField(blank=True, max_length=100)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('optimized_sequence', models.IntegerField(blank=True, help_text='AI suggested visit order', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_points', to='routes.route')),
            ],
            options={
                'ordering': ['optimized_sequence', 'id'],
            },
        ),
    ]
